[book]
authors = ["Haobo Gu"]
language = "en"
multilingual = true
src = "src"
title = "RMK Documentation"

[build]
build-dir = "book"                # the directory where the output is placed
create-missing = true             # whether or not to create missing pages
extra-watch-dirs = ["po"]             # directories to watch for triggering builds

[preprocessor.gettext]
after = ["links"]

[output.xgettext]
optional = true
pot-file = "messages.pot"
granularity = 0

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
curly-quotes = false
mathjax-support = false
copy-fonts = true
no-section-label = true
git-repository-url = "https://github.com/HaoboGu/rmk"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/HaoboGu/rmk/docs/{path}"
additional-css = [
  "theme/css/language-picker.css",
]

[output.html.fold]
enable = true
level = 0