[build]
target = "riscv32imafc-unknown-none-elf"

[target.riscv32imafc-unknown-none-elf]
# runner = 'riscv64-unknown-elf-gdb -x ../../openocd.gdb'
runner = [
    "probe-rs", "run",
    "--chip", "HPM5361",
    "--chip-description-path", "HPMicro.yaml",
    "--protocol","jtag",
    "--log-format", "{t} {L} {F}:{l} {s}",
]
linker = "flip-link"
rustflags = [
    # Target features:
    # The default for imacf is is "+m,+a,+c,+f"
    "-C",
    "target-feature=+zba,+zbb,+zbc,+zbs",
    # Linker scripts:
    "-C",
    "link-arg=-Tmemory.x",
    "-C",
    "link-arg=-Tdevice.x",     # __VECTORED_INTERRUPTS
    "-C",
    "link-arg=-Tlink-fixed.x",
    "-C",
    "link-arg=-Tdefmt.x",
    "-C",
    "link-arg=-nmagic",

    # "--emit", "obj",
    # "--emit", "asm",
]

[unstable]
build-std = ["core"]

[env]
DEFMT_LOG = "trace"
