name: Build

on:
  push:
    branches: ["main"]
    paths: ["examples/**", "rmk/**", "rmk-config/**", "rmk-macro/**"]
  pull_request:
    branches: ["main"]
    paths: ["examples/**", "rmk/**", "rmk-config/**", "rmk-macro/**"]

# Cancel any currently running workflows from the same PR, branch, or
# tag when a new workflow is triggered.
#
# https://stackoverflow.com/a/66336834
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install target
        run: rustup target add thumbv7em-none-eabihf thumbv6m-none-eabi thumbv7em-none-eabi
      - name: Install cargo-make
        run: cargo install --force cargo-make
      - name: Build rmk
        working-directory: ./rmk
        run: cargo build --release 
      - name: Build rp2040
        working-directory: ./examples/use_rust/rp2040
        run: cargo make uf2 --release
      - name: Build rp2040 with config
        working-directory: ./examples/use_config/rp2040
        run: cargo make uf2 --release
      - name: Build stm32h7
        working-directory: ./examples/use_rust/stm32h7
        run: cargo make uf2 --release
      - name: Build stm32h7 with config
        working-directory: ./examples/use_config/stm32h7
        run: cargo make uf2 --release
      - name: Build stm32f1
        working-directory: ./examples/use_rust/stm32f1
        run: cargo make uf2 --release
      - name: Build stm32f1 with config
        working-directory: ./examples/use_config/stm32f1
        run: cargo make uf2 --release
      - name: Build stm32f4
        working-directory: ./examples/use_rust/stm32f4
        run: cargo make uf2 --release
      - name: Build stm32f4 with config
        working-directory: ./examples/use_config/stm32f4
        run: cargo make uf2 --release
      - name: Build nrf52840_ble
        working-directory: ./examples/use_rust/nrf52840_ble
        run: cargo make uf2 --release
      - name: Build nrf52832_ble
        working-directory: ./examples/use_rust/nrf52832_ble
        run: cargo make uf2 --release
      - name: Build nrf52840_ble with config
        working-directory: ./examples/use_config/nrf52840_ble
        run: cargo make uf2 --release
      - name: Build nrf52832_ble with config
        working-directory: ./examples/use_config/nrf52832_ble
        run: cargo make uf2 --release
      - name: Build rp2040 split
        working-directory: ./examples/use_rust/rp2040_split
        run: cargo make uf2 --release
      - name: Build rp2040 split with config
        working-directory: ./examples/use_config/rp2040_split
        run: cargo make uf2 --release
      - name: Build nrf52840 split
        working-directory: ./examples/use_rust/nrf52840_ble_split
        run: cargo make uf2 --release
      - name: Build rp2040 split with config
        working-directory: ./examples/use_config/nrf52840_ble_split
        run: cargo make uf2 --release
        